### PR TITLE
#2: makes sure list of lessons is sorted

### LINKED ISSUE #2: Sometimes list of lessons isn't sorted
Sometimes after I finish a lesson and look up the list of lessons with -l, the order is all mixed up.
It seems to happen randomly.

### PR DESCRIPTION
**Pull request by pektinasen**
This fixes #2.
I guess it took longer for some of the Promises returned by loadLessons to be executed than for others. So this Commit waits for all of them to be resolved and then sorts the returned list of lessons.

### CODE REVIEW

**Comment by F1LT3R** [comment]
Looks great. Thanks @pektinasen! I will run this later and merge if everything looks good.

**Comment by F1LT3R** [comment]
Confirmed incorrect ordering in Master. Nice catch.

screen shot 2016-06-09 at 12 50 46 pm

Your PR looks like it takes care of things.

screen shot 2016-06-09 at 12 51 38 pm

I'll merge this now.
Thanks for the contribution!

**Comment by quadro9** [comment]
and would you update npm package?

**Comment by F1LT3R** [comment]
Will do.

**Comment by F1LT3R** [comment]
Done. @1.0.2

**Pull request merged**
